apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: clothesshop-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: clothesshop
  policy:
    semver:
      range: 1.x
